// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api_proto/v1/fuck.proto

package api_protov1connect

import (
	v1 "api/api_proto/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FuckServiceName is the fully-qualified name of the FuckService service.
	FuckServiceName = "api_proto.v1.FuckService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FuckServiceFuckProcedure is the fully-qualified name of the FuckService's Fuck RPC.
	FuckServiceFuckProcedure = "/api_proto.v1.FuckService/Fuck"
)

// FuckServiceClient is a client for the api_proto.v1.FuckService service.
type FuckServiceClient interface {
	Fuck(context.Context, *v1.FuckRequest) (*v1.FuckResponse, error)
}

// NewFuckServiceClient constructs a client for the api_proto.v1.FuckService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFuckServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FuckServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fuckServiceMethods := v1.File_api_proto_v1_fuck_proto.Services().ByName("FuckService").Methods()
	return &fuckServiceClient{
		fuck: connect.NewClient[v1.FuckRequest, v1.FuckResponse](
			httpClient,
			baseURL+FuckServiceFuckProcedure,
			connect.WithSchema(fuckServiceMethods.ByName("Fuck")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fuckServiceClient implements FuckServiceClient.
type fuckServiceClient struct {
	fuck *connect.Client[v1.FuckRequest, v1.FuckResponse]
}

// Fuck calls api_proto.v1.FuckService.Fuck.
func (c *fuckServiceClient) Fuck(ctx context.Context, req *v1.FuckRequest) (*v1.FuckResponse, error) {
	response, err := c.fuck.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// FuckServiceHandler is an implementation of the api_proto.v1.FuckService service.
type FuckServiceHandler interface {
	Fuck(context.Context, *v1.FuckRequest) (*v1.FuckResponse, error)
}

// NewFuckServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFuckServiceHandler(svc FuckServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fuckServiceMethods := v1.File_api_proto_v1_fuck_proto.Services().ByName("FuckService").Methods()
	fuckServiceFuckHandler := connect.NewUnaryHandlerSimple(
		FuckServiceFuckProcedure,
		svc.Fuck,
		connect.WithSchema(fuckServiceMethods.ByName("Fuck")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api_proto.v1.FuckService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FuckServiceFuckProcedure:
			fuckServiceFuckHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFuckServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFuckServiceHandler struct{}

func (UnimplementedFuckServiceHandler) Fuck(context.Context, *v1.FuckRequest) (*v1.FuckResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api_proto.v1.FuckService.Fuck is not implemented"))
}
