// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file api_proto/v1/fuck.proto (package api_proto.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api_proto/v1/fuck.proto.
 */
export const file_api_proto_v1_fuck: GenFile = /*@__PURE__*/
  fileDesc("ChdhcGlfcHJvdG8vdjEvZnVjay5wcm90bxIMYXBpX3Byb3RvLnYxIiYKC0Z1Y2tSZXF1ZXN0EhcKBG5hbWUYASABKAlCCbpIBnIEEAEYAiIcCgxGdWNrUmVzcG9uc2USDAoEZnVjaxgBIAEoCTJOCgtGdWNrU2VydmljZRI/CgRGdWNrEhkuYXBpX3Byb3RvLnYxLkZ1Y2tSZXF1ZXN0GhouYXBpX3Byb3RvLnYxLkZ1Y2tSZXNwb25zZSIAQogBChBjb20uYXBpX3Byb3RvLnYxQglGdWNrUHJvdG9QAVocYXBpL2FwaV9wcm90by92MTthcGlfcHJvdG92MaICA0FYWKoCC0FwaVByb3RvLlYxygILQXBpUHJvdG9cVjHiAhdBcGlQcm90b1xWMVxHUEJNZXRhZGF0YeoCDEFwaVByb3RvOjpWMWIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * @generated from message api_proto.v1.FuckRequest
 */
export type FuckRequest = Message<"api_proto.v1.FuckRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api_proto.v1.FuckRequest.
 * Use `create(FuckRequestSchema)` to create a new message.
 */
export const FuckRequestSchema: GenMessage<FuckRequest> = /*@__PURE__*/
  messageDesc(file_api_proto_v1_fuck, 0);

/**
 * @generated from message api_proto.v1.FuckResponse
 */
export type FuckResponse = Message<"api_proto.v1.FuckResponse"> & {
  /**
   * @generated from field: string fuck = 1;
   */
  fuck: string;
};

/**
 * Describes the message api_proto.v1.FuckResponse.
 * Use `create(FuckResponseSchema)` to create a new message.
 */
export const FuckResponseSchema: GenMessage<FuckResponse> = /*@__PURE__*/
  messageDesc(file_api_proto_v1_fuck, 1);

/**
 * @generated from service api_proto.v1.FuckService
 */
export const FuckService: GenService<{
  /**
   * @generated from rpc api_proto.v1.FuckService.Fuck
   */
  fuck: {
    methodKind: "unary";
    input: typeof FuckRequestSchema;
    output: typeof FuckResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_proto_v1_fuck, 0);

