// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file api_proto/v1/greet.proto (package api_proto.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api_proto/v1/greet.proto.
 */
export const file_api_proto_v1_greet: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGlfcHJvdG8vdjEvZ3JlZXQucHJvdG8SDGFwaV9wcm90by52MSInCgxHcmVldFJlcXVlc3QSFwoEbmFtZRgBIAEoCUIJukgGcgQQARgCIiEKDUdyZWV0UmVzcG9uc2USEAoIZ3JlZXRpbmcYASABKAkyUgoMR3JlZXRTZXJ2aWNlEkIKBUdyZWV0EhouYXBpX3Byb3RvLnYxLkdyZWV0UmVxdWVzdBobLmFwaV9wcm90by52MS5HcmVldFJlc3BvbnNlIgBCiQEKEGNvbS5hcGlfcHJvdG8udjFCCkdyZWV0UHJvdG9QAVocYXBpL2FwaV9wcm90by92MTthcGlfcHJvdG92MaICA0FYWKoCC0FwaVByb3RvLlYxygILQXBpUHJvdG9cVjHiAhdBcGlQcm90b1xWMVxHUEJNZXRhZGF0YeoCDEFwaVByb3RvOjpWMWIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * @generated from message api_proto.v1.GreetRequest
 */
export type GreetRequest = Message<"api_proto.v1.GreetRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message api_proto.v1.GreetRequest.
 * Use `create(GreetRequestSchema)` to create a new message.
 */
export const GreetRequestSchema: GenMessage<GreetRequest> = /*@__PURE__*/
  messageDesc(file_api_proto_v1_greet, 0);

/**
 * @generated from message api_proto.v1.GreetResponse
 */
export type GreetResponse = Message<"api_proto.v1.GreetResponse"> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string;
};

/**
 * Describes the message api_proto.v1.GreetResponse.
 * Use `create(GreetResponseSchema)` to create a new message.
 */
export const GreetResponseSchema: GenMessage<GreetResponse> = /*@__PURE__*/
  messageDesc(file_api_proto_v1_greet, 1);

/**
 * @generated from service api_proto.v1.GreetService
 */
export const GreetService: GenService<{
  /**
   * @generated from rpc api_proto.v1.GreetService.Greet
   */
  greet: {
    methodKind: "unary";
    input: typeof GreetRequestSchema;
    output: typeof GreetResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_proto_v1_greet, 0);

