// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api_proto/v1/fuck.proto

package api_protov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FuckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuckRequest) Reset() {
	*x = FuckRequest{}
	mi := &file_api_proto_v1_fuck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuckRequest) ProtoMessage() {}

func (x *FuckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fuck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuckRequest.ProtoReflect.Descriptor instead.
func (*FuckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fuck_proto_rawDescGZIP(), []int{0}
}

func (x *FuckRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FuckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fuck          string                 `protobuf:"bytes,1,opt,name=fuck,proto3" json:"fuck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuckResponse) Reset() {
	*x = FuckResponse{}
	mi := &file_api_proto_v1_fuck_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuckResponse) ProtoMessage() {}

func (x *FuckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fuck_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuckResponse.ProtoReflect.Descriptor instead.
func (*FuckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fuck_proto_rawDescGZIP(), []int{1}
}

func (x *FuckResponse) GetFuck() string {
	if x != nil {
		return x.Fuck
	}
	return ""
}

var File_api_proto_v1_fuck_proto protoreflect.FileDescriptor

const file_api_proto_v1_fuck_proto_rawDesc = "" +
	"\n" +
	"\x17api_proto/v1/fuck.proto\x12\fapi_proto.v1\x1a\x1bbuf/validate/validate.proto\",\n" +
	"\vFuckRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\x02R\x04name\"\"\n" +
	"\fFuckResponse\x12\x12\n" +
	"\x04fuck\x18\x01 \x01(\tR\x04fuck2N\n" +
	"\vFuckService\x12?\n" +
	"\x04Fuck\x12\x19.api_proto.v1.FuckRequest\x1a\x1a.api_proto.v1.FuckResponse\"\x00B\x88\x01\n" +
	"\x10com.api_proto.v1B\tFuckProtoP\x01Z\x1capi/api_proto/v1;api_protov1\xa2\x02\x03AXX\xaa\x02\vApiProto.V1\xca\x02\vApiProto\\V1\xe2\x02\x17ApiProto\\V1\\GPBMetadata\xea\x02\fApiProto::V1b\x06proto3"

var (
	file_api_proto_v1_fuck_proto_rawDescOnce sync.Once
	file_api_proto_v1_fuck_proto_rawDescData []byte
)

func file_api_proto_v1_fuck_proto_rawDescGZIP() []byte {
	file_api_proto_v1_fuck_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_fuck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_fuck_proto_rawDesc), len(file_api_proto_v1_fuck_proto_rawDesc)))
	})
	return file_api_proto_v1_fuck_proto_rawDescData
}

var file_api_proto_v1_fuck_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_fuck_proto_goTypes = []any{
	(*FuckRequest)(nil),  // 0: api_proto.v1.FuckRequest
	(*FuckResponse)(nil), // 1: api_proto.v1.FuckResponse
}
var file_api_proto_v1_fuck_proto_depIdxs = []int32{
	0, // 0: api_proto.v1.FuckService.Fuck:input_type -> api_proto.v1.FuckRequest
	1, // 1: api_proto.v1.FuckService.Fuck:output_type -> api_proto.v1.FuckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_fuck_proto_init() }
func file_api_proto_v1_fuck_proto_init() {
	if File_api_proto_v1_fuck_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_fuck_proto_rawDesc), len(file_api_proto_v1_fuck_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_fuck_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_fuck_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_fuck_proto_msgTypes,
	}.Build()
	File_api_proto_v1_fuck_proto = out.File
	file_api_proto_v1_fuck_proto_goTypes = nil
	file_api_proto_v1_fuck_proto_depIdxs = nil
}
