package main

import (
	"context"
	"fmt"
	"net/http"

	v1 "api/api_proto/v1"                 // generated by protoc-gen-go
	"api/api_proto/v1/api_protov1connect" // generated by protoc-gen-connect-go

	"connectrpc.com/connect"
	"connectrpc.com/validate"
)

type GreetServer struct{}

func (s *GreetServer) Greet(
	_ context.Context,
	req *v1.GreetRequest,
) (*v1.GreetResponse, error) {
	res := &v1.GreetResponse{
		Greeting: fmt.Sprintf("Hello, %s!", req.GetName()),
	}
	return res, nil
}

type FuckServer struct{}

func (s *FuckServer) Fuck(
	_ context.Context,
	req *v1.FuckRequest,
) (*v1.FuckResponse, error) {
	res := &v1.FuckResponse{
		Fuck: fmt.Sprintf("Fuck you, %s!", req.GetName()),
	}
	return res, nil
}

func main() {
	greeter := &GreetServer{}
	mux := http.NewServeMux()
	path, handler := api_protov1connect.NewGreetServiceHandler(
		greeter,
		// Validation via Protovalidate is almost always recommended
		connect.WithInterceptors(validate.NewInterceptor()),
	)
	mux.Handle(path, handler)

	fucker := &FuckServer{}
	path, handler = api_protov1connect.NewFuckServiceHandler(
		fucker,
		connect.WithInterceptors(validate.NewInterceptor()),
	)
	mux.Handle(path, handler)

	p := new(http.Protocols)
	p.SetHTTP1(true)
	// Use h2c so we can serve HTTP/2 without TLS.
	p.SetUnencryptedHTTP2(true)
	s := http.Server{
		Addr:      "localhost:8080",
		Handler:   mux,
		Protocols: p,
	}
	s.ListenAndServe()
}
